import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAppSelector } from '../lib/redux/hooks';
import { fetchWithAuth } from '../lib/api';
import Logo from './Logo';

type Preview = { status: string; creator?: { display_name: string; avatar?: string | null } };
type InviteKind = 'chat' | 'space' | null;

export default function InvitePage() {
  const { token = '' } = useParams(); const navigate = useNavigate(); const user = useAppSelector(state => state.user.user);
  const [preview, setPreview] = useState<Preview | null>(null); const [kind, setKind] = useState<InviteKind>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { const load = async () => { const chat = await fetchWithAuth(`/chats/invites/${encodeURIComponent(token)}/preview`); const chatData = await chat.json(); if (chatData.status !== 'invalid') { setKind('chat'); setPreview(chatData); return; } const space = await fetchWithAuth(`/spaces/invites/${encodeURIComponent(token)}/preview`); setKind('space'); setPreview(await space.json()); }; void load().catch(() => setPreview({ status: 'invalid' })); }, [token]);
  const accept = async () => { if (!kind) return; if (!user) { sessionStorage.setItem(kind === 'chat' ? 'queenchat_pending_chat_invite' : 'queenchat_pending_invite', token); navigate('/register'); return; } setBusy(true); const response = await fetchWithAuth(`/${kind === 'chat' ? 'chats/invites' : 'spaces/invites'}/${encodeURIComponent(token)}/accept`, { method: 'POST' }); if (response.ok) { const data = await response.json(); sessionStorage.removeItem('queenchat_pending_chat_invite'); sessionStorage.removeItem('queenchat_pending_invite'); navigate(kind === 'space' ? `/chat/${data.chat_id}/space` : `/chat/${data.chat_id}`, { replace: true }); } else { setPreview({ status: (await response.json()).detail || 'invalid' }); setBusy(false); } };
  const stateText: Record<string, string> = { expired: 'Срок действия приглашения истёк', used: 'Приглашение уже использовано', revoked: 'Приглашение больше не действительно', invalid: 'Такого приглашения нет' };
  const isChat = kind === 'chat';
  return <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-950 via-purple-950 to-fuchsia-950 p-5 text-center text-white"><section className="w-full max-w-md rounded-3xl border border-white/15 bg-white/10 p-8 shadow-2xl backdrop-blur-xl"><div className="mb-8 flex justify-center"><Logo variant="full" /></div>{preview?.status === 'active' ? <><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-violet-500 text-3xl">{preview.creator?.avatar ? <img src={preview.creator.avatar} className="h-full w-full object-cover" /> : preview.creator?.display_name?.[0]}</div><h1 className="text-2xl font-bold">{preview.creator?.display_name} приглашает тебя {isChat ? 'в QueenChat' : 'в общее пространство'}</h1><p className="mt-4 text-purple-100">{isChat ? 'Начните общаться в личном чате' : 'Фотографии, важные моменты, заметки и планы — только для вас двоих.'}</p><button onClick={() => void accept()} disabled={busy} className="mt-8 w-full rounded-2xl bg-gradient-to-r from-violet-500 to-pink-500 px-5 py-3 font-semibold disabled:opacity-60">{busy ? 'Подключаем…' : isChat ? 'Присоединиться' : 'Принять'}</button>{!user && <button onClick={() => { sessionStorage.setItem(isChat ? 'queenchat_pending_chat_invite' : 'queenchat_pending_invite', token); navigate('/login'); }} className="mt-3 text-sm text-purple-200 underline">У меня уже есть аккаунт</button>}</> : <><div className="text-5xl">💌</div><h1 className="mt-5 text-2xl font-bold">{stateText[preview?.status || 'invalid']}</h1><button onClick={() => navigate('/')} className="mt-8 rounded-xl bg-white/10 px-5 py-3">На главную</button></>}</section></main>;
}
