import { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { fetchWithAuth } from '../lib/api';

type Space = { title: string; theme: string; created_at: number; participants: { id: string; display_name: string; avatar?: string }[]; stats: { messages: number; photos: number; memories: number; days: number } };
export default function SpacePage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [space, setSpace] = useState<Space | null>(null); const [missing, setMissing] = useState(false); const [items, setItems] = useState<any[]>([]);
  const section = location.pathname.split('/space/')[1]?.split('/')[0] || '';
  const load = () => fetchWithAuth(`/spaces/${id}`).then(async r => r.ok ? setSpace(await r.json()) : setMissing(true)).catch(() => setMissing(true));
  useEffect(() => { void load(); }, [id]);
  useEffect(() => { if (section && ['photos', 'memories', 'dates', 'notes'].includes(section)) fetchWithAuth(`/spaces/${id}/${section}`).then(r => r.ok ? r.json() : []).then(setItems).catch(() => setItems([])); }, [id, section]);
  const activate = async () => { const r = await fetchWithAuth(`/spaces/${id}/activate`, { method: 'POST', body: JSON.stringify({ theme: 'queen' }) }); if (r.ok) { setMissing(false); load(); } };
  if (missing) return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-violet-950 to-pink-950 p-6 text-white"><button onClick={() => navigate(`/chat/${id}`)} className="text-purple-200">← В чат</button><section className="mx-auto mt-24 max-w-md rounded-3xl border border-white/15 bg-white/10 p-8 text-center backdrop-blur"><div className="text-5xl">💜</div><h1 className="mt-5 text-2xl font-bold">Наше пространство</h1><p className="mt-3 text-purple-100">Сохраняйте важное, планируйте и будьте ближе.</p><button onClick={activate} className="mt-7 rounded-2xl bg-gradient-to-r from-violet-500 to-pink-500 px-6 py-3 font-semibold">Создать пространство</button></section></main>;
  if (!space) return <div className="min-h-screen bg-slate-950" />;
  if (section) return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-violet-950 to-pink-950 p-5 text-white"><button onClick={() => navigate(`/chat/${id}/space`)} className="text-purple-200">← Наше пространство</button><section className="mx-auto max-w-2xl py-8"><h1 className="text-3xl font-bold">{{ photos: 'Фото', memories: 'Воспоминания', dates: 'Важные даты', notes: 'Заметки', settings: 'Оформление' }[section] || 'Наше пространство'}</h1>{section === 'settings' ? <div className="mt-6 flex flex-wrap gap-3">{['queen', 'sunset', 'midnight', 'rose', 'aurora'].map(theme => <button key={theme} onClick={async () => { await fetchWithAuth(`/spaces/${id}/settings`, { method: 'PUT', body: JSON.stringify({ theme }) }); load(); }} className={`rounded-2xl px-4 py-3 capitalize ${space.theme === theme ? 'bg-pink-500' : 'bg-white/10'}`}>{theme}</button>)}</div> : <div className={section === 'photos' ? 'mt-6 grid grid-cols-3 gap-2' : 'mt-6 space-y-3'}>{items.length ? items.map(item => section === 'photos' ? item.images.map((url: string) => <img key={`${item.id}-${url}`} src={url} className="aspect-square w-full rounded-xl object-cover" />) : <article key={item.id} className="rounded-2xl bg-white/10 p-4 backdrop-blur"><b>{item.title || item.author}</b>{item.event_date && <p className="mt-1 text-pink-200">{item.event_date}</p>}{item.content && <p className="mt-2 text-purple-100">{item.content}</p>}{item.images?.map((url: string) => <img key={url} src={url} className="mt-3 max-h-48 rounded-xl" />)}</article>) : <p className="mt-8 text-purple-200">Пока здесь тихо — это только начало вашей истории.</p>}</div>}</section></main>;
  return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-violet-950 to-pink-950 p-5 text-white"><button onClick={() => navigate(`/chat/${id}`)} className="text-purple-200">← В чат</button><section className="mx-auto max-w-2xl py-8"><div className="rounded-3xl border border-white/15 bg-white/10 p-7 shadow-xl backdrop-blur"><div className="flex -space-x-3">{space.participants.map(p => <div key={p.id} className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-full border-2 border-violet-900 bg-pink-400 font-bold">{p.avatar ? <img src={p.avatar} className="h-full w-full object-cover" /> : p.display_name[0]}</div>)}</div><p className="mt-6 text-sm text-pink-200">Ваше пространство</p><h1 className="text-3xl font-bold">{space.title}</h1><p className="mt-2 text-purple-100">Вместе здесь {space.stats.days} дн.</p></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Чат', `/chat/${id}`], ['Фото', `/chat/${id}/space/photos`], ['Воспоминания', `/chat/${id}/space/memories`], ['Даты', `/chat/${id}/space/dates`], ['Заметки', `/chat/${id}/space/notes`], ['Оформление', `/chat/${id}/space/settings`]].map(([name, url]) => <button key={name} onClick={() => navigate(url)} className="rounded-2xl bg-white/10 p-5 text-left backdrop-blur hover:bg-white/15">{name}</button>)}</div><div className="mt-5 grid grid-cols-4 gap-3 text-center">{[['Сообщений', space.stats.messages], ['Фото', space.stats.photos], ['Воспоминаний', space.stats.memories], ['Дней', space.stats.days]].map(([label, value]) => <div key={label as string} className="rounded-2xl bg-black/20 p-4"><b className="block text-xl">{value}</b><span className="text-xs text-purple-200">{label as string}</span></div>)}</div></section></main>;
}
